const commonData = {
    "card-making": [
      "Greeting Cards",
      "Holiday Cards",
      "Invitation Cards",
      "Pop-up Cards",
      "Shaker Cards",
      "Interactive Cards",
      "Embossed Cards",
      "Die-cut Cards",
      "Watercolor Cards",
      "Stamped Cards",
    ],
    "scrapbooking": [
      "Layouts",
      "Mini Albums",
      "Pocket Pages",
      "Travel Journals",
      "Baby Books",
      "Wedding Albums",
      "Heritage Albums",
      "Mixed Media Scrapbooks",
      "Digital Scrapbooking",
      "Smash Books",
    ],
    "paper-quilling-and-origami": [
      "Quilled Flowers",
      "Quilled Animals",
      "Quilled Jewelry",
      "Quilled Cards",
      "Origami Animals",
      "Origami Flowers",
      "Origami Boxes",
      "Modular Origami",
      "Origami Decorations",
      "Origami for Kids",
    ],
    "glass-painting": [
      "Stained Glass",
      "Suncatchers",
      "Glass Ornaments",
      "Glass Bottles & Jars",
      "Glassware Painting",
      "Reverse Glass Painting",
      "Glass Panels",
      "Glass Tiles",
      "Faux Stained Glass",
      "Glass Painting Techniques",
    ],
    "lampworking": [
      "Glass Beads",
      "Pendants",
      "Earrings",
      "Bracelets",
      "Necklaces",
      "Marbles",
      "Sculptural Pieces",
      "Glass Figurines",
      "Wine Stoppers",
      "Glass Pipes",
    ],
    "glass-dying-and-staining": [
      "Glass Dyeing Techniques",
      "Glass Staining Techniques",
      "Stained Glass Windows",
      "Glass Vases",
      "Glass Jars",
      "Glass Candle Holders",
      "Glass Sculptures",
      "Glass Mosaics",
      "Glass Tiles",
      "Glass Fusing and Slumping",
    ],
  };

  export default commonData;